routes/web.php
<?php

/*

LARAVEL Debug bar: https://github.com/barryvdh/laravel-debugbar
*/

Route::get('/', 'NewsController@index')->name('homepage');



/*Route::get('/', function() {
	return view('welcome');
});*/

Auth::routes();

/*
Sukuriami 7 route'ai reikalingi CRUD operacijoms, sarasas:
https://laravel.com/docs/5.8/controllers#resource-controllers
*/

Route::get('naujienos/autorius/{id}', 'NewsController@authorIndex')->name('naujienos.author');

Route::resource('naujienos', 'NewsController');
Route::resource('comments', 'CommentController');
Route::resource('categories', 'CategoryController');

Route::get('search', 'SearchController@index')->name('search');

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Comment;
use App\Http\Requests\StoreBlogPost;
use App\NewsCategories;
use App\NewsItem;
use App\User;
use Illuminate\Http\Request;

use Auth;
use Illuminate\Support\Facades\Log;

class NewsController extends Controller {

	public function __construct() {

		// konstruktoriuje aprase middleware, galime pasirinkti kokioms funkcijoms jis pritaikomas
		$this->middleware( 'auth' )->except( [ 'index', 'show' ] );
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		//
		$news = NewsItem::with( 'user')
						->with('categories')
						->with('comments')
						->orderBy( 'title' )
						->paginate( 50 );


		Log::info( $news );

		return view( 'news.index', compact( 'news' ) );

	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		// gauname visas kategorijas
		$categories = Category::all();



		return view( 'news.create', compact( 'categories' ) );
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store( StoreBlogPost $request ) {
		//patikriname atkeliavusi requesta

		/* laravel colective formos: https://laravelcollective.com/docs/6.0/html */


		$newsItem             = new NewsItem();
		$newsItem->title      = $request->input( 'title' );
		$newsItem->content    = $request->input( 'content' );
		$newsItem->main_image = "none";

		// gauname prisijungusio vartotojo informacija
		$newsItem->user_id = Auth::user()->id;

		$cat =$request->input('category');

		$newsItem->save();

		// Visada pries sukuriant relationship'a reikia iskviesti save() funkcija
		// nes kitu atveju naujiena dar neturi savo ID
		$newsItem->categories()->attach($cat);



		session()->flash( 'message', 'Sekmingai sukurta naujiena' );

//		session()->flash('error', 'Sekmingai sukurta naujiena');

		return redirect()->route( 'naujienos.index' );
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show( $id ) {

		/*
		Laravel eager loading:
		https://laravel.com/docs/5.8/eloquent-relationships#eager-loading
		*/
		$newsItem = NewsItem::findOrFail($id);

		/* Laravel log viewer package'as :
		https://github.com/rap2hpoutre/laravel-log-viewer
		*/
//		Log::info( $newsItem->user );

		return view( 'news.show', compact( 'newsItem' ) );
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit( $id ) {
		//
		$newsItem = NewsItem::find($id);

		//$selectedCategories = $newsItem->categories->pluck('id')->toArray();


		$selectedCategories = [];
		foreach ($newsItem->categories as $cat) {
			$selectedCategories[] = $cat->id;
		}

		$categories = Category::all();

		return view('news.edit', compact(['newsItem', 'categories', 'selectedCategories']));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update( Request $request, $id ) {
		//

		$newsItem = NewsItem::find($id);

		$newsItem->title = $request->input('title');
		$newsItem->content = $request->input('content');


		$categories = $request->input('category');

		$newsItem->categories()->sync($categories);

		$newsItem->save();

		return redirect()->back();
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( $id ) {
		//
		$newsItem = NewsItem::find( $id );
		$newsItem->delete();

		// rodyti vartotojui pranesima apie sekmingai istrinta naujiena
		session()->flash( 'message', 'Sekmingai istrinta naujiena' );

		return redirect()->back();
	}

	public function authorIndex(Request $request,  $id ) {
		$user = User::with( 'news' )->find( $id );


		$order = 'title';
		if(!empty($request->input('order'))) {
			$order =$request->input('order');
		}

		$charCount = $user->totalCharacters();

		/*$newsCount = 0;
		foreach($user->news as $newsItem) {
			// suzinau koks yra naujienos turinio ilgis
			// ir pridedu prie bendro kintamojo, kur saugau informacija
			$newsCount += strlen($newsItem->content);
		}*/

		return view( 'news.author', compact( ['user', 'order'] ) );
	}
}

resources/views/news/author.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                Autorius: {{ $user->name }}
            </div>

            <div class="col-6">
                <form method="get">
                    <select name="order">
                        <option value="title">Pavadinimas</option>
                        <option value="created_at">Sukurimo data</option>
                    </select>

                    <input type="submit" value="rikiuoti" />
                </form>
                <h2>Autoriaus naujienos</h2>
                @foreach($user->news($order)->get() as $newsItem)
                    <div class="col-6 mt-3">
                        <h4>
                            {{ $newsItem->title }}
                        </h4>

                        <div>
                            Autorius:
                            <a href="{{ route('naujienos.author', $newsItem->user_id) }}">
                                {{ $newsItem->user->email }}
                            </a>

                        </div>

                        <div>
                            <a href="{{ route('naujienos.show', $newsItem->id) }}">
                                Skaityti daugiau
                            </a>
                        </div>

                    </div>
                @endforeach
            </div>

            <div class="col-6">
                autoriaus parasytu simboliu kiekis: {{ $user->totalCharacters() }} simboliai


                <h3>Vartotojo komentarai</h3>

                @foreach($user->comments as $comment)
                    @include('comments.singleComment')
                @endforeach
            </div>


        </div>
    </div>
@endsection

resources/views/news/create.blade.php
@extends('layouts.app')

@section('content')
    <form method="post" action="{{ route('naujienos.store') }}">
        <div class="container">
            <div class="row">
                <div class="col-8">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <h1>Sukurti naujiena</h1>


                    @csrf

                    <input class="form-control" value="{{ old('title') }}" name="title"/>

                    <textarea id="content" name="content" class="form-control">{{ old('content') }}</textarea>

                    <input type="submit" id="save" class="btn btn-success"/>
                </div>

                <div class="col-4">
                    <h3>Naujienos kategorijos</h3>

                    {{--<select name="category" class="form-control">
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">
                                {{ $category->name }}
                            </option>
                        @endforeach
                    </select>--}}


                    @foreach($categories as $category)
                        <input type="checkbox" name="category[]" value="{{ $category->id }}">
                        {{ $category->name }}
                    @endforeach

                </div>
            </div>
        </div>
    </form>

    <script>
        // noredami pasinaudoti ckeditor, naudojame CKEDITOR.replace funkcija
        // kaip parametra perduodame textarea elemento ID

        // PAPILDOMAI: layouts/app.blade.php faile nuimti defer attributa nuo app.js failo include'o
        CKEDITOR.replace('content');
    </script>
@endsection

resources/views/news/edit.blade.php
@extends('layouts.app')

@section('content')
    <form method="post" action="{{ route('naujienos.update', $newsItem->id) }}">
        @method('put')
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <h1>Redaguoti naujiena</h1>


                    @csrf

                    <input class="form-control" value="{{ $newsItem->title }}" name="title"/>

                    <textarea id="content" name="content" class="form-control">{{ $newsItem->content }}</textarea>

                    <input type="submit" id="save" class="btn btn-success"/>
                </div>

                <div class="col-4">
                    <h3>Naujienos kategorijos</h3>
                    @foreach($categories as $category)
                        @if(in_array($category->id, $selectedCategories))
                            <input type="checkbox" checked name="category[]" value="{{ $category->id }}">
                            {{ $category->name }}
                            @else
                            <input type="checkbox" name="category[]" value="{{ $category->id }}">
                            {{ $category->name }}
                            @endif

                    @endforeach

                </div>
            </div>
        </div>
    </form>

    <script>
        // noredami pasinaudoti ckeditor, naudojame CKEDITOR.replace funkcija
        // kaip parametra perduodame textarea elemento ID

        // PAPILDOMAI: layouts/app.blade.php faile nuimti defer attributa nuo app.js failo include'o
        CKEDITOR.replace('content');
    </script>
@endsection

resources/views/news/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @if(isset($search))
                <div class="col-12">
                    Naujienos pagal uzklausa: {{ $search }}
                </div>
            @else
                <div class="col-12">
                   Visos naujienos
                </div>
            @endif

            @foreach($news as $newsItem)
                <div class="col-6 mt-3">
                    <img src="{{ $newsItem->main_image }}" />

                    <h4>
                        {{ $newsItem->title }}
                        {{-- Komentaru kiekis teisingas budas: --}}

                        <a href="{{ route('naujienos.show', $newsItem->id) }}#comments">
                            ({{ $newsItem->comments->count() }})
                        </a>


                        {{-- Komentaru kiekis neteisingas budas: --}}
                        {{--({{ count($newsItem->comments) }})--}}
                    </h4>

                    <div>
                        Autorius:
                        <a href="{{ route('naujienos.author', $newsItem->user_id) }}">
                            {{ $newsItem->user->fullName() }}
                        </a>

                        Kategorija:
                        @foreach($newsItem->categories  as $category)
                            {{ $category->name }}
                        @endforeach

                    </div>

                    <p>
                        {!! $newsItem->execerpt(20) !!}
                    </p>

                    <div>
                        <a href="{{ route('naujienos.show', $newsItem->id) }}">
                            Skaityti daugiau
                        </a>
                    </div>
                    @auth
                        {{-- Scenarijus kai esi prisijunges --}}
                        <form method="post" action="{{ route('naujienos.destroy', $newsItem->id) }}">
                            @csrf
                            {{-- Kadangi naudojame resource controlleri, butinai turime nurodyti
                                metoda delete
                            --}}
                            @method('delete')

                            <input type="submit" class="btn-danger btn" value="Trinti">
                        </form>
                    @else
                        {{-- Scenarijus kai esi neprisijunges--}}
                    @endauth




                    {{-- Tikrinimas is kito galo --}}
                    @guest
                        {{--kazka rodau jei esi neprisijunges----}}
                    @else
                        {{-- kazka rodau jei esi prisijunges--}}
                    @endguest


                </div>
            @endforeach

            @if(count($news) == 0)
                <div class="col-12">
                    <h1>Nieko nerasta.... </h1>
                </div>

            @endif

            {{-- Paginacija --}}

            {{ $news->links() }}
        </div>
    </div>
@endsection

resources/views/news/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                <img src="{{ $newsItem->main_image }}" />
                <h1>{{ $newsItem->title }}</h1>
                Kategorija:
                @foreach($newsItem->categories  as $category)
                    {{ $category->name }}
                @endforeach


                <a href="{{ route('naujienos.edit', $newsItem->id) }}" class="btn btn-warning">
                    Redaguoti naujiena
                </a>
            </div>
            <div class="col-6 mt-3">
                <h4>
                    {{ $newsItem->title }}
                </h4>

                <p>
                    {{-- Stilizuota ir formatuota teksta isvedame su tokia sintakse: --}}
                    {!! $newsItem->content !!}
                </p>

            </div>

            <div class="col-12" id="comments">
                <hr>
                <h3>Komentarai</h3>

                @auth
                    <form action="{{ route('comments.store') }}" method="post">
                        @csrf

                        <div class="form-group">
                            <textarea class="form-control" placeholder="Iveskite komentara" required
                                      name="comment_text"></textarea>
                        </div>
                        {{-- Perduodame kuriai naujienai priklauso komentaras --}}
                        <input type="hidden" name="news_id" value="{{ $newsItem->id }}">

                        <input type="submit" class="btn btn-success" value="Rasyti komentara"/>
                    </form>
                @else
                    <p>Noredami rasyti komentarus, <a href="{{ route('login') }}">prisijunkite</a></p>
                @endauth
            </div>

            <div class="col-12">
                <hr>

                @foreach($newsItem->comments as $comment)
                    @include('comments.singleComment')
                @endforeach
            </div>
        </div>
    </div>

    <script>
        CKEDITOR.replace('comment_text');
    </script>
@endsection